language: rust
dist: xenial
cache: 
  cargo: true
  directories:
    - $HOME/.cargo
    - $HOME/.cache
rust:
  - stable
os:
  - linux
env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"
    - CARGO_MAKE_KCOV_INSTALLATION_DIRECTORY="$HOME/.cache/kcov"
    - CARGO_MAKE_COVERAGE_PROVIDER="tarpaulin"
addons:
  apt:
    packages:
      - libgsl0-dev
      - samtools
      - curl
      - libcurl3
      - libelf1
      - libdw1
      - cmake
      - gcc 
      - binutils
install:
  - command -v cargo-tarpaulin >/dev/null 2>&1 || cargo install cargo-tarpaulin
  - command -v cargo-make >/dev/null 2>&1 || cargo install --debug cargo-make
script:
  - cargo make ci-flow
