language: rust

rust:
  - stable

cache: cargo

sudo: false

# Dependencies of kcov, used for cargo-travis
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - libgsl0-dev
    sources:
      - kalakris-cmake

before_script:
  - which cargo-coveralls || cargo install cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test -- --test-threads=1

after_success:
  - cargo coveralls
