[package]
name = "libprosic"
version = "0.7.1-alpha.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>", "David Lähnemann <david.laehnemann@uni-duesseldorf.de>"]
description = "A library for calling of genomic variants using a latent variable model."
repository = "https://github.com/prosic/libprosic"
readme = "README.md"
license = "GPL-3.0"
include = ["src/**/*", "Cargo.toml", "CHANGELOG.md", "README.md", "LICENSE"]

[dependencies]
bio = { git = "https://github.com/rust-bio/rust-bio.git", branch = "optimize-pairhmm" }
log = "0.3"
rust-htslib = "0.22"
GSL = "1.0"
itertools = "0.6"
itertools-num = "0.1"
approx = "0.1"
rusty-machine="0.4"
ordered-float = "0.5"
ndarray = "0.6"
quick-error = "1.2"
vec_map = "0.8"
regex = "0.2"

serde = "1"
serde_derive = "1"
csv = "1.0.0-beta.5"
lazy_static = "0.2"
cached = "0.7.0"
statrs = "0.9"

[dev-dependencies]
env_logger = "0.3"
fern = "0.4"
flate2 = "0.2"
hyper = "0.10"

[features]
default = []
gslv2 = ["GSL/v2"]
