[package]
name = "libprosic"
version = "0.3.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A library for calling of genomic variants using a latent variable model."
repository = "https://github.com/prosic/libprosic"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
bio = "0.13.*"
log = "0.3.*"
rust-htslib = "0.11.*"
GSL = "0.4.*"
itertools = "0.5.*"
itertools-num = "0.1.*"
approx = "0.1.*"
rusty-machine="0.4.*"
ordered-float = "0.2.*"
ndarray = "0.6"
flame = { version = "^0.1.2", optional = true }
flamer = { version = "^0.1.2", optional = true }
rustc-serialize = "0.3.*"
quick-error = "1.1.*"
csv = "0.14.*"
lazy_static = "0.2.*"
statrs = "0.6.*"

[dev-dependencies]
env_logger = "0.3.*"
fern = "0.4"
flate2 = "0.2"
hyper = "0.10"

[features]
default = []
flame_it = ["flame", "flamer"]
