name: PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title-format:
    runs-on: ubuntu-latest
    steps:
      - uses: kunalnagarco/action-semantic-pr@v1.2.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}